networks:
  default:
    name: light-addict-bot

volumes:
    mongo-volume:

services:
  mongo:
    image: mongo:5
    restart: always
    volumes:
      - mongo-volume:/data/db

  app:
    image: atrush/light-addict-bot
    restart: always
    ports:
      - 80:80
    environment:
      - TELEGRAM_BOT_TOKEN=""
      - DEVICES_SERVER_PORT="80"
      - DB_HOST="mongo"
    depends_on:
      - mongo
