networks:
  default:
    name: power-outage-bot

services:
  mongo:
    image: mongo:5
    restart: always
    volumes:
      - ./data/mongo:/data/db

  power-outage-bot:
    image: atrush/power-outage-bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=
      - DEVICES_SERVER_PORT=80
      - DB_HOST=mongo
    depends_on:
      - mongo

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
